#!/bin/bash

echo "Loading libcomposite"

modprobe libcomposite
CONFIGFS_ROOT=/sys/kernel/config
cd "${CONFIGFS_ROOT}"/usb_gadget
mkdir g1
cd g1

echo 0xa4ac > idVendor
echo 0x0525 > idProduct

mkdir strings/0x409
echo "some Company" > strings/0x409/manufacturer
echo "frosted Flakes" > strings/0x409/product
mkdir configs/c.1
mkdir configs/c.1/strings/0x409

echo "usb_dun" > configs/c.1/strings/0x409/configuration
mkdir functions/ffs.usb
ln -s functions/ffs.usb configs/c.1

# wait for some time for daemon-usb to fill the endpoints
echo "complete"